[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["dotnet-sdk_9", "postgresql"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet build -c Release",
  "dotnet ef database update",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/SawirahMunicipalityWeb.dll"
