[build]
builder="dockerfile"
dockerfilepath="./SawirahMunicipalityWeb/Dockerfile"

[deploy]
startCommand = "dotnet SawirahMunicipalityWeb.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
